import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FE",
    paddingBottom: 100,
  },
  headerContainer: {
    marginBottom: 16,
  },
  gradientHeader: {
    backgroundColor: "#667EEA",
    borderRadius: 30,
    padding: 20,
    shadowColor: "#667EEA",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  hello: {
    fontSize: 14,
    color: "#FFFFFF",
    opacity: 0.9,
    marginBottom: 4,
  },
  name: {
    fontSize: 25,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  avatarWrapper: {
    position: "relative",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  avatarText: {
    fontSize: 22,
    fontWeight: "700",
    color: "#667EEA",
  },
  onlineDot: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#4ADE80",
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  statsRow: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 16,
    padding: 12,
    justifyContent: "space-around",
  },
  statBox: {
    alignItems: "center",
    flex: 1,
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 10,
    color: "#FFFFFF",
    opacity: 0.9,
  },
  statDivider: {
    width: 1,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    marginHorizontal: 10,
  },
  searchBox: {
    marginHorizontal: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 24,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  searchText: {
    flex: 1,
    color: "#A0AEC0",
    fontSize: 15,
  },
  filterButton: {
    backgroundColor: "#667EEA",
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  filterIcon: {
    fontSize: 16,
  },
  categoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  categoryCard: {
    width: width * 0.28,
    borderRadius: 20,
    padding: 14,
    alignItems: "center",
  },
  categoryIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  categoryIcon: {
    fontSize: 22,
  },
  categoryText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 4,
  },
  categoryCount: {
    fontSize: 11,
    color: "#718096",
    fontWeight: "600",
  },
  sectionHeader: {
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 2,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#A0AEC0",
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  seeAll: {
    color: "#667EEA",
    fontWeight: "700",
    fontSize: 13,
    marginRight: 4,
  },
  arrow: {
    color: "#667EEA",
    fontSize: 14,
    fontWeight: "700",
  },
  collectionScroll: {
    marginBottom: 28,
    paddingLeft: 20,
  },
  collectionCard: {
    width: 160,
    borderRadius: 20,
    marginBottom: 16,
    padding: 16,
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  collectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  collectionEmoji: {
    fontSize: 32,
  },
  moreButton: {
    width: 24,
    height: 24,
    backgroundColor: "rgba(0,0,0,0.05)",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  moreText: {
    fontSize: 16,
    color: "#718096",
    fontWeight: "700",
  },
  collectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 4,
  },
  collectionCount: {
    fontSize: 12,
    color: "#718096",
    marginBottom: 12,
  },
  collectionFooter: {
    marginTop: 8,
  },
  progressBar: {
    height: 4,
    backgroundColor: "rgba(0,0,0,0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    width: "65%",
    backgroundColor: "#667EEA",
    borderRadius: 2,
  },
  recentCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    marginHorizontal: 20,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  recentIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  recentIcon: {
    fontSize: 28,
  },
  recentContent: {
    flex: 1,
  },
  recentTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 6,
    lineHeight: 20,
  },
  recentFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  recentSubtitle: {
    fontSize: 12,
    color: "#718096",
  },
  recentDot: {
    fontSize: 12,
    color: "#CBD5E0",
    marginHorizontal: 6,
  },
  recentTime: {
    fontSize: 12,
    color: "#A0AEC0",
  },
  moreIconButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  moreIcon: {
    fontSize: 20,
    color: "#A0AEC0",
    fontWeight: "700",
  },

  // Dropdown Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  dropdown: {
    position: "absolute",
    top: 90,
    right: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    width: 280,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
    overflow: "hidden",
  },
  dropdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#F7FAFC",
  },
  dropdownAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#667EEA",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  dropdownAvatarText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  dropdownName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 2,
  },
  dropdownEmail: {
    fontSize: 12,
    color: "#718096",
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    paddingVertical: 14,
  },
  dropdownIcon: {
    fontSize: 20,
    marginRight: 12,
    width: 30,
  },
  dropdownLabel: {
    flex: 1,
    fontSize: 15,
    color: "#2D3748",
    fontWeight: "600",
  },
  dangerText: {
    color: "#E53E3E",
  },
  badge: {
    backgroundColor: "#667EEA",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: "center",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },
});
